## Foragingmodel Parameter File ##



# -------------------------- Initialisation parameters ------------------------------------ #

init_birds = 100	# number of birds on September, 1
# include distributions for bird initialisation here as well 

resolution_min = 30 	# time step size in minutes

# IR at which 623g bird with mean efficienty needs 12 hours of foraging 
leaving_threshold = 0.02045685 # kJ/s


# ----------------------------------- Prey Characteristics -------------------------------- #

# conversion to AFDW and energy content of shellfish prey
AFDWenergyContent = 22.5 	# kJ / gram	ZwartEnsDurellEtAl1996
RatioAFDWtoWet = 0.16 		# afdw per g wtw	ZwartEnsDurellEtAl1996

# conversion cockle FW to size
CockFWtoSizeA = 14.610 		# Ens
CockFWtoSizeB = 0.317766

# mussel data
mussel_density = 99999 		# infinite density
mussel_wtw_gain = -0.0025 	# wtw gain per day, GossCustard2001
mussel_afdw = 0.85 			# start weight, g AFDW GossCustard2001


# ----------------------- Food digestion and assimilation parameters ---------------------- #

FractionTakenUp = 0.85	# Speakman1987,KerstenVisser1996,KerstenPiersma1987,ZwartsBlomert1996
LeftOverShellfish = 0.1 # ZwartEnsKerstenetal1996

