## Foragingmodel Parameter File ##


# -------------------------- Initialisation parameters ------------------------------------ #

resolution_min = 30 		# time step size in minutes
init_birds = 10000			# number of birds on September, 1

# worm specialist distributions 
w_mussel_foraging_efficiency = 0
w_cockle_foraging_mean = 0.8
w_macoma_foraging_mean = 1
w_worm_foraging_efficiency = 1

# shellfish specialist distributions
s_mussel_foraging_mean = 1
s_cockle_foraging_mean = 1
s_macoma_foraging_mean = 0.8
s_worm_foraging_efficiency = 0


# IR at which 623g bird with mean efficienty needs 12 hours of foraging 
leaving_threshold = 0.02045685 # kJ/s

time_foraged_init = 8 		# time foraged in previous cycle
init_stomach_content = 0	# stomach content, g
start_weight = 548.9		# start weight of bird (reference weight on sept 1, g)


# ----------------------------------- Prey Characteristics -------------------------------- #

# conversion to AFDW and energy content of shellfish prey
AFDWenergyContent = 22.5 	# kJ / gram	ZwartEnsDurellEtAl1996
RatioAFDWtoWet = 0.16 		# afdw per g wtw	ZwartEnsDurellEtAl1996

# conversion cockle FW to size
CockFWtoSizeA = 14.610 		# Ens
CockFWtoSizeB = 0.317766

# conversion wet weight to afdw for worms
conversion_afdw_wtw = 0.17 	# conversion from thesis Jeroen Onrust

# mussel data
mussel_density = 99999 		# infinite density
mussel_wtw_gain = -0.0025 	# wtw gain per day, GossCustard2001
mussel_afdw = 0.85 			# start weight, g AFDW GossCustard2001


# ----------------------------- Functional Response Parameters ---------------------------- #

# handling time cockles
leoA = 0.000860373					# Zwarts et al.(1996b), taken from WEBTICS
leoB = 0.220524 			
leoC = 1.79206

# functional response mudflats
hiddinkA = 0.000625					# Hiddink, 2003
hiddinkB = 0.000213					# handling parameter

# functional response mussel
attack_rate = 0.00057  				# mosselA in webtics
mussel_intake_rate_A = 0.092  		# parameters for max intake rate (plateau)
mussel_intake_rate_B = 0.506


# --------------------------------- Interference Parameters ------------------------------- #

# interference on mudflats
attack_distance = 2.0  			# webtics, stillman 2002
alpha = 0.4  					# fitted parameter by webtics

# interference on mussel beds, Stillman1996
competitors_threshold = 158 	# density of competitors above which interference occurs ha-1
a = 0.437 						# parameters for stabbers 
b = -0.00721


# ----------------------- Food digestion and assimilation parameters ---------------------- #

# fraction prey taken up from stomach and left over fraction
LeftOverShellfish = 0.1 # ZwartEnsKerstenetal1996
FractionTakenUp = 0.85	# Speakman1987,KerstenVisser1996,KerstenPiersma1987,ZwartsBlomert1996

# stomach content and digestion rates
max_digestive_rate = 0.263 			# g WtW / min, KerstenVisser1996
deposition_efficiency = 0.75		# WEBTICS page 57
BodyGramEnergyCont = 34.295  		# kJ/gram fat, conversion fat to energy
BodyGramEnergyReq = 45.72666666		# kJ/gram (25% larger) conversion energy to fat
minimum_weight = 450				# g
max_stomach_content = 80 			# g WtW KerstenVisser1996

# energy requirements
thermo_a = 904     		# kerstenpiersma 1987 kJ/day
thermo_b = 30.3
metabolic_a = 0.061 	# zwartsenskerstenetal1996 kJ/day
metabolic_b = 1.489

# ----------------------------- Sensitivity Analysis Parameters --------------------------- #

relative_density = 1 		# relative prey density
relative_threshold = 1		# relative leaving_threshold
agg_factor_mudflats = 8 	# aggregation factor on mudflats
agg_factor_bed = 8			# aggregation factor on mussel beds